__default__ :
        job-name      : "{rule}"
        output        : "logs/{rule}/{wildcards}.out"
        ntasks        : 1
        cpus-per-task : 1
        mem           : "200M"
        time          : "00-00:05:00"
        account       : "my_account"
        partition     : "my_partition"

# Override the above defaults with job specific values
#bwa_mem :
#        cpus-per-task : 16
#        mem           : "10000M"
#        time          : "00-01:00:00"

#fastqc_raw :
#	cpus-per-task  : 1
#	mem	       : "200M"
#	time           : "00-01:40:00"

# Job specific resource requirements can be passed from the rule, in the Snakefile, via the "resources" keyword

pbindex :
        cpus-per-task : 1
        mem           : "200"
        time          : "00-01:00:00"

ccs :
        cpus-per-task : 10
        mem           : "4000"
        time          : "00-03:30:00"

pbmerge :
        cpus-per-task : 1
        mem           : "100"
        time          : "00-00:10:00"

pbmerge_sample :
        cpus-per-task : 1
        mem           : "500"
        time          : "00-00:30:00"

bbduk :
        cpus-per-task : 10
        mem           : "2000"
        time          : "00-00:06:00"

bbduk_genome :
        cpus-per-task : 20
        mem           : "10000"
        time          : "00-00:05:00"


seqtk :
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:0{resources.time}:00"


bbmap_sort:
        cpus-per-task : 1 
        mem           : "70000"
        time          : "00-04:00:00"

select_longest:
        cpus-per-task : 1
        mem           : "2000"
        time          : "00-00:40:00"

flye:
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

canu:
        cpus-per-task : 1
        mem           : "50"
        time          : "00-04:00:00"

hifiasm:
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

gfa2fa:
        cpus-per-task : 1
        mem           : 500
        time          : "00-00:01:00"

hifiasm_mummer:
        cpus-per-task : 1
        mem           : "500"
        time          : "00-00:02:00"

hifiasm_quast:
        cpus-per-task : 1
        mem           : "500"
        time          : "00-00:01:00"

quast :
        cpus-per-task : 1
        mem           : "500"
        time          : "00-00:{resources.time}:00"

quastref :
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

mummer :
        cpus-per-task : "{resources.cpu}"
        mem           : "{resources.mem_mb}"
        time          : "00-00:{resources.time}:00"

busco:
        cpus-per-task : 10
        mem           : "30000"
        time          : "00-05:00:00"

gt_ltrharvest:
        cpus-per-task : 10
        mem           : "10000"
        time          : "00-00:35:00"

ltr_finder:
        cpus-per-task : 10
        mem           : "5000"
        time          : "00-00:07:00"

ltr_retriever:
        cpus-per-task : 10
        mem           : "20000"
        time          : "00-03:30:00"

